---
kind: Service
apiVersion: v1
metadata:
  name: springboot-app-service
spec:
  selector:
    app: springboot-app
  ports:
  - protocol: "TCP"
    port: 8081
    targetPort: 8080
    nodePort: 30002
  type: LoadBalancer

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: springboot-app-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
      - name: springboot-app
        image: sasoria/rest-service:latest
        ports:
        - containerPort: 8080
