#!/bin/bash
echo "[msg] building springboot-service..."
sleep 2
cd springboot-service/
bash deploy.sh

echo "---------------------------------"
cd ..

echo "[msg] building angular-service..."
cd angular-service/
sleep 2
bash deploy.sh