#!/bin/bash

ROOT_DIR=$(pwd)

# Build springboot-service
echo "[log] building springboot-service..."
sleep 2
cd $ROOT_DIR/services/springboot-service/
bash deploy.sh

# Build node-service
echo "[log] building node-service..."
cd $ROOT_DIR/services/node-service/
sleep 2
bash deploy.sh