#!/bin/bash

# Install script for Skatteetatens architect

git clone https://github.com/Skatteetaten/architect.git

# Setup GO
# TODO implement this

echo "run with,
	$ bin/amd_64/architect build -f test.json -v "
