#!/bin/bash

# Install script for Skatteetatens architect

git clone https://github.com/Skatteetaten/architect.git

if [ !$(type -P go) ]; then
    echo "please install go and set up $PATH varaiables
    export GOROOT=...
    export GOPATH=...
    export PATH=$GOROOT/bin:$PATH"
fi

echo "run with,
	$ ./bin/amd64/architect build -f test.json -v "
