---
kind: Service
apiVersion: v1
metadata:
  name: rest-app-service
spec:
  selector:
    app: rest-app
  ports:
  - protocol: "TCP"
    port: 8081
    targetPort: 8080
    nodePort: 30002
  type: LoadBalancer

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rest-app-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: rest-app
    spec:
      containers:
      - name: rest-app
        image: sasoria/rest-service:latest
        ports:
        - containerPort: 8080