---
kind: Service
apiVersion: v1
metadata:
  name: node-app-service
spec:
  selector:
    app: node-app
  ports:
  - protocol: "TCP"
    port: 8081
    targetPort: 8000
    nodePort: 30003
  type: LoadBalancer

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: sasoria/node-service:latest
        ports:
        - containerPort: 8000
